#define SF_ARG1	8
#define SF_ARG2	16
#define SF_ARG3	24
#define SF_ARG4	32
#define SF_ARG5	40
#define SF_ARG6	48
#define SF_ARG7	52
#define SF_ARG8	56

#define TRUE  1
#define FALSE 0
#define NULL  0

#define STDOUT 0
#define STDERR 1
#define STDIN  2

#define __BUFSIZ__ 2048

#define EXIT_FAIL 1
#define EXIT_OK   0

#define I64_MIN 0x8000000000000000
#define I64_MAX 0x7fffffffffffffff
#define U64_MAX 0xffffffffffffffff
#define U8_MAX  0xFF
#define I8_MAX  0x7F
#define I8_MIN  0xFFFFFF80

