#ifndef IR_INLINE_H
#define IR_INLINE_H

/* Inline-related transforms for the IR backend.
 *
 * The parser recognises the `inline` keyword and sets AST_FLAG_INLINE
 * on the function definition, but no longer expands calls at parse
 * time - inline calls reach the IR pipeline as ordinary AST_FUNCALLs.
 * The plan is to splice them at the IR level so the inlined body
 * benefits from mem2reg / fold / peephole alongside the caller. This
 * module is the groundwork:
 *
 *   - irClearRecursiveInline scans every AST_FUNC marked
 *     AST_FLAG_INLINE for direct self-recursion and drops the flag
 *     (with a user-facing warning) on offenders. Recursive functions
 *     can't be inlined so the IR pipeline treats them as ordinary
 *     calls.
 *
 *   - irFunctionClone produces a deep copy of an IrFunction's blocks
 *     and instructions with fresh tmp / block ids. Used by the future
 *     splice pass; not wired into the codegen yet. */

#include "ast.h"
#include "cctrl.h"
#include "containers.h"
#include "ir-types.h"
#include "list.h"

/* Bundle returned by irFunctionClone. The blocks list is in the same
 * order as the source's; the entry / exit pointers are the cloned
 * counterparts of src->entry_block / src->exit_block. tmp_remap maps
 * source tmp ids to cloned tmp ids so callers can post-process
 * (e.g. re-bind params at a call site). */
typedef struct IrCloneResult {
    List   *blocks;       /* List<IrBlock *> */
    IrBlock *entry_block;
    IrBlock *exit_block;
    Map    *tmp_remap;    /* Map<u32 src_tmp_id -> u32 new_tmp_id> */
    Map    *block_remap;  /* Map<u32 src_block_id -> IrBlock *> */
} IrCloneResult;

/* Direct-recursion check: for every AST_FUNC marked AST_FLAG_INLINE,
 * walks its body looking for an AST_FUNCALL of itself by name. If
 * found, emits a warning and clears AST_FLAG_INLINE (leaving the
 * function as a normal callable). Mutual recursion is not yet
 * detected; we'll add SCC-based cycle detection when needed. */
void irClearRecursiveInline(Cctrl *cc);

/* One-time pre-pass that lowers every AST_FUNC marked AST_FLAG_INLINE
 * to a fresh IrFunction and stashes it in an internal cache keyed by
 * function name. The cache feeds the splice pass at every IR_CALL
 * site. Idempotent. */
void irInlineCacheBuild(Cctrl *cc);

/* Look up the cached IR for an inline-flagged function by its name
 * (the args wrapper's `as.array.label`). Returns NULL when the name
 * is unknown or the function isn't marked inline. */
IrFunction *irInlineCacheGet(AoStr *fname);

/* Splice-in every IR_CALL in `caller` whose callee is in the inline
 * cache. Currently handles only the simplest shape: callee has a
 * single basic block ending in one IR_RET. Multi-block / multi-RET
 * callees fall back to a normal call (the cache lookup matches but
 * the splice declines and leaves the IR_CALL intact). Runs before
 * mem2reg / fold so the inlined body benefits from those passes. */
void irInlineSplice(IrFunction *caller);

/* Deep-clone every block / instruction / value of `src`. New tmp ids
 * are allocated against the global ir_tmp_var_id counter, new block
 * ids against ir_block_id; both are caller-namespace so the result
 * can be spliced into another function without further renaming. The
 * result's instruction operands are remapped (TMP -> cloned TMP,
 * block targets in JMP/BR/LOOP and phi-pair blocks -> cloned blocks);
 * IR_VAL_LOCAL / globals / constants / labels are shared with the
 * source.
 *
 * If `param_subst` is non-NULL, IR_VAL_PARAM operand references are
 * looked up by their var.id and replaced with the substituted
 * IrValue* (this is what the splice pass uses to bind the callee's
 * parameters to the call site's argument values).
 *
 * Caveats:
 *   - IR_SWITCH (extra.cases) is not yet supported; will panic.
 *   - IR_VAL_PHI as an operand kind isn't generated by the lowering
 *     path the IR backend uses, so it's not handled. */
IrCloneResult *irFunctionClone(IrFunction *src, Map *param_subst);

/* Free the IrCloneResult and its maps. Does NOT free the cloned
 * blocks / instructions / values - those remain available for the
 * caller to splice into a target function. */
void irCloneResultRelease(IrCloneResult *r);

#endif
